-- Run this in Supabase Dashboard -> SQL Editor

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

-- Public visitors can submit contact messages.
drop policy if exists "Allow public contact form inserts" on public.contact_messages;

create policy "Allow public contact form inserts"
on public.contact_messages
for insert
to anon, authenticated
with check (
  length(trim(name)) between 2 and 100
  and length(trim(email)) between 5 and 200
  and length(trim(subject)) between 2 and 200
  and length(trim(message)) between 10 and 5000
);

-- No public SELECT policy is intentionally created.
-- Visitors can submit, but cannot read your contact messages.
